version: 2

sources:
  - name: raw
    database: sublime-cargo-475009-k1
    schema: gz_raw_data
    loader: bigquery
    description: this is the raw data
    freshness:
       warn_after: {count: 12, period: hour}
       error_after: {count: 24, period: hour}
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: this is the raw sales data
        tests:
            - unique:
                column_name: "( orders_id || '-' ||  pdt_id )"
      - name: adwords
        identifier: raw_gz_adwords
        description: this is the raw adwords data



      - name: facebook
        identifier: raw_gz_facebook
        description: this is the raw facebook data



      - name: criteo
        identifier: raw_gz_criteo
        description: this is the raw criteo data


      - name: bing
        identifier: raw_gz_bing
        description: this is the raw bing data

             
                 
      - name: product
        identifier: raw_gz_product
        description: this is the raw product data
        columns:
          - name: products_id
            tests:
              - unique
              - not_null


      - name: ship
        identifier: raw_gz_ship
        description: this is the raw shipping data
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null         

models:
  - name: int_sales_margin
    description: joining sales and product to obtain pruchase cost and margin calcs
    columns:
      - name: orders_id
        description: order_id
        tests:
          - not_null
      - name: products_id
        description: products_id
      - name: date_date
        description: date of order
  - name: int_orders_margin
    description: margins by orders
    columns:
      - name: orders_id
        description: order_id
        tests:
          - unique
          - not_null
  - name: int_orders_operational
    description: orders to ship for op costs
    columns:
      - name: date_date
        description: date of orders
        tests: 
          - not_null

  - name: finance_days
    description: daily KPIs
    columns:
      - name: date_date
        description: date of orders
        tests: 
          - unique
          - not_null
      - name: nb_transactions
        description: number of transactions
      - name: total_revenue
        description: total rev calc
      - name: avg_basket
        description: averaging basket size, revn/order_num
      - name: operating_margin
        description: operating margin
      - name: total_purchase_cost
        description: sum of purchase cost
      - name: total_ship_fee
        description: sum of ship_fee
      - name: total_log_cost
        description: sum of log_cost
      - name: total_quantity
        description: sum of quantity

  - name: int_campaigns
    description: combines all 4 ad campaigns
    tests: 
      - unique:
          column_name: "(date_date || '-' || campaign_key)"


  - name: int_campaigns_day
    description: campaign day aggregated
    columns:
      - name: date_date
        description: date
        tests:
          - not_null