version: 2

sources:
  - name: raw
    database: sublime-cargo-475009-k1
    schema: gz_raw_data
    loader: bigquery
    description: this is the raw data
    freshness:
       warn_after: {count: 12, period: hour}
       error_after: {count: 24, period: hour}
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: this is the raw sales data
        tests:
            - unique:
                column_name: "( orders_id || '-' ||  pdt_id )"
                 
      - name: product
        identifier: raw_gz_product
        description: this is the raw product data
        columns:
          - name: products_id
            tests:
              - unique
              - not_null


      - name: ship
        identifier: raw_gz_ship
        description: this is the raw shipping data
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null         

models:
  - name: int_orders_margin
    description: calculates the orderds margin
    columns:
      - name: orders_id
        description: id for each order 
        tests:
            - unique
            - not_null    

  - name: int_orders_operational
    description: calculates the orderds margin and joined ship
    columns:
      - name: orders_id
        description: id for each order 
        tests:
            - unique
            - not_null    


  - name: int_sales_margin
    description: calculates the sales margin
    columns:
      - name: orders_id
        description: id for each order 
        tests:
            - not_null    

